<?php

function imagecache_textactions_install() {
  if (function_exists('imagecache_action_definitions')) {
    imagecache_action_definitions(TRUE);
  }
  cache_clear_all('imagecache_actions', 'cache');
}
function imagecache_textactions_uninstall() {
  if (function_exists('imagecache_action_definitions')) {
    imagecache_action_definitions(TRUE);
  }
  cache_clear_all('imagecache_actions', 'cache');
}