<?php
// $Id$

function imagecache_canvasactions_install() {
  if (function_exists('imagecache_action_definitions')) {
    imagecache_action_definitions(TRUE);
  }
  cache_clear_all('imagecache_actions', 'cache');
}
function imagecache_canvasactions_uninstall() {
  if (function_exists('imagecache_action_definitions')) {
    imagecache_action_definitions(TRUE);
  }
  cache_clear_all('imagecache_actions', 'cache');
}